In [1]:
import numpy as np

In [9]:
W = np.array([[-1/2, 1/3, 0, 0, 0, 2/3],
              [1/3, -1, 1/3, 0, 0, 0],
              [0, 2/3, -1, 1/3, 0, 0],
              [0, 0,2/3, -1, 1/3, 0],
              [0, 0, 0, 2/3, -1, 1/3],
              [1/6,0, 0, 0, 2/3, -1]])
np.linalg.eig(W)[0]

array([ 1.40027360e-16+0.j        , -4.43855875e-01+0.23750143j,
       -4.43855875e-01-0.23750143j, -1.88153191e+00+0.j        ,
       -1.36537817e+00+0.19705002j, -1.36537817e+00-0.19705002j])

In [10]:
def simulator(Δt, sims, π0, W):
    for _ in range(sims):
        π0 += W@π0
    
    return π0

In [11]:
Δt = 1
sims = 100
π0 = np.random.rand(6)
π0 = π0/np.sum(π0) #Normalize initial pdf

π_SS = simulator(Δt, sims, π0, W)
π_SS #2/7 for p(0), and 1/7 for every other state (correct)

array([0.28571424, 0.14285718, 0.14285708, 0.14285722, 0.14285706,
       0.14285722])

In [14]:
"""
Another example
"""
π0 = np.random.rand(4)
π0_norm = π0 / np.sum(π0)
Δt = 1
sims = 100
W = np.array([[-0.6, 0.2, 0, 0],
             [0.6, -0.8, 0.2, 0.5],
             [0, 0.5, -0.2, 0.5],
             [0, 0.1, 0, -1.0]])
π_SS = simulator(Δt, sims, π0_norm, W)
π_SS

array([0.07968127, 0.23904382, 0.65737052, 0.02390438])