In [1]:
import numpy as np

In [67]:
N = np.array([[1, -1, -1, -1, 0, 0, 0],
             [0, 2, 0, 0, -2, -1, 0],
             [0, 0, 1, -1, 1, 0, 0],
             [0, 0, 0, 1, 0, 0, -1]])
v = np.array([[0.5, 0.2, 0.1, 1.2, 5, 1.2, 2]]) # Fluxes' values
dX = np.dot(N, v.T)
dX # Change in concentration of each specie

array([[ -1. ],
       [-10.8],
       [  3.9],
       [ -0.8]])

In [21]:
# v2, v4 and v5 are independent fluxes
# idx - 1
order = np.array([1, 3, 4, 0, 2, 5, 6])
N_new = N[:, order]
N_new

array([[-1, -1,  0,  1, -1,  0,  0],
       [ 2,  0, -2,  0,  0, -1,  0],
       [ 0, -1,  1,  0,  1,  0,  0],
       [ 0,  1,  0,  0,  0,  0, -1]])

In [24]:
N_I = N_new[:, [0,1,2]]
N_D = N_new[:, [3,4,5,6]]

In [33]:
N_D_plus = np.dot(np.linalg.inv(np.dot(N_D.T, N_D)), N_D.T)
N_D_plus

array([[ 1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0.,  0., -1.]])

In [39]:
v_I = np.array([[1, 2.5, 0.3]])
v_D = - np.dot(np.dot(N_D_plus, N_I), v_I.T)
v_D

array([[5.7],
       [2.2],
       [1.4],
       [2.5]])

In [40]:
np.linalg.matrix_rank(N)

4

In [58]:
from scipy.linalg import null_space
C = null_space(N)
C

array([[ 0.0633458 ,  0.286476  ,  0.7297092 ],
       [ 0.55918008,  0.31553498,  0.01124518],
       [-0.5504092 ,  0.04950927,  0.31090256],
       [ 0.05457492, -0.07856825,  0.40756145],
       [ 0.60498412, -0.12807753,  0.09665889],
       [-0.09160809,  0.88722501, -0.17082742],
       [ 0.05457492, -0.07856825,  0.40756145]])

In [59]:
np.dot(N, C) #should ~ 0

array([[ 1.24900090e-16, -4.16333634e-17, -1.11022302e-16],
       [-1.11022302e-16, -2.22044605e-16,  2.77555756e-17],
       [ 1.11022302e-16, -5.55111512e-17, -2.49800181e-16],
       [-9.02056208e-17,  5.55111512e-17,  2.22044605e-16]])

In [62]:
n_conserv = np.linalg.matrix_rank(N) - 4 #4 is the number of species
n_conserv

0

In [75]:
N = np.array([[-1, 1, 0, 0],
             [1, -1, 0, 0],
             [1, 0, -1, 0],
             [0, -1, 0, 1]])
λ, λ_vec = np.linalg.eig(N.T)
print(f"{N[λ == 0,:]}") #Where's the other dependent row?

[[-1  1  0  0]]


In [80]:
n_conserv = N.shape[0] - np.linalg.matrix_rank(N)
n_conserv # 1 conservation relationship

1

In [97]:
C = null_space(N)
#Given an initial concentration vector
X = np.array([[1, 1.2, 0.5, 2.3]])
R = np.dot(C, X)
R #Conservation relationships?

array([[0.5 , 0.6 , 0.25, 1.15],
       [0.5 , 0.6 , 0.25, 1.15],
       [0.5 , 0.6 , 0.25, 1.15],
       [0.5 , 0.6 , 0.25, 1.15]])