In [1]:
import numpy as np

In [2]:
N = np.array([[1, -1, -1, -1, 0, 0, 0],
             [0, 2, 0, 0, -2, -1, 0],
             [0, 0, 1, -1, 1, 0, 0],
             [0, 0, 0, 1, 0, 0, -1]])
v = np.array([[0.5, 0.2, 0.1, 1.2, 5, 1.2, 2]]) # Fluxes' values
dX = np.dot(N, v.T)
dX # Change in concentration of each specie

array([[ -1. ],
       [-10.8],
       [  3.9],
       [ -0.8]])

In [3]:
# v2, v4 and v5 are independent fluxes
# idx - 1
order = np.array([1, 3, 4, 0, 2, 5, 6])
N_new = N[:, order]
N_new

array([[-1, -1,  0,  1, -1,  0,  0],
       [ 2,  0, -2,  0,  0, -1,  0],
       [ 0, -1,  1,  0,  1,  0,  0],
       [ 0,  1,  0,  0,  0,  0, -1]])

In [4]:
N_I = N_new[:, [0,1,2]]
N_D = N_new[:, [3,4,5,6]]

In [5]:
N_D_plus = np.dot(np.linalg.inv(np.dot(N_D.T, N_D)), N_D.T)
N_D_plus

array([[ 1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0.,  0., -1.]])

In [6]:
v_I = np.array([[1, 2.5, 0.3]])
v_D = - np.dot(np.dot(N_D_plus, N_I), v_I.T)
v_D

array([[5.7],
       [2.2],
       [1.4],
       [2.5]])

In [7]:
np.linalg.matrix_rank(N) # Expecting 0 conservation relationships

4

In [8]:
from scipy.linalg import null_space
C = null_space(N.T)
C # Agrees with the 0 c.r. predicted

array([], shape=(4, 0), dtype=float64)

In [9]:
np.dot(N, C) #should ~ 0 ; it is

ValueError: shapes (4,7) and (4,0) not aligned: 7 (dim 1) != 4 (dim 0)

In [62]:
n_conserv = np.linalg.matrix_rank(N) - 4 #4 is the number of species
n_conserv

0

In [10]:
N = np.array([[-1, 1, 0, 0],
             [1, -1, 0, 0],
             [1, 0, -1, 0],
             [0, -1, 0, 1]])
λ, λ_vec = np.linalg.eig(N.T)
print(f"{N[λ == 0,:]}") #Where's the other dependent row?

[[-1  1  0  0]]


In [11]:
n_conserv = N.shape[0] - np.linalg.matrix_rank(N)
n_conserv # 1 conservation relationship

1

In [14]:
C = null_space(N.T)
C #This is my conservation relationship

array([[-7.07106781e-01],
       [-7.07106781e-01],
       [-5.55111512e-17],
       [-1.11022302e-16]])